# Q1

In [3]:
import pandas as pd
import selenium
from bs4 import BeautifulSoup
import time
from selenium import webdriver
import requests
import re
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException
from selenium.webdriver.support.ui import WebDriverWait

In [4]:
#get the web driver
driver=webdriver.Chrome(r"C:\Users\dell\Downloads\chromedriver_win32\chromedriver.exe")

C:\Users\DELL\AppData\Local\Temp/ipykernel_2040/3250302793.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r"C:\Users\dell\Downloads\chromedriver_win32\chromedriver.exe")

In [3]:
# Getting the webpage of mentioned url 
url=('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')
driver.get(url)

In [4]:
# Creating empty list for storing data after scraping

Rank = []
Name = []
Artist = []
UploadDate = []
Views = []

In [7]:
from selenium.webdriver.common.by import By

In [6]:
# Scraping Rank of the videos
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[1]"):
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append("_")

Rank

['1.',
 '2.',
 '3.',
 '4.',
 '5.',
 '6.',
 '7.',
 '8.',
 '9.',
 '10.',
 '11.',
 '12.',
 '13.',
 '14.',
 '15.',
 '16.',
 '17.',
 '18.',
 '19.',
 '20.',
 '21.',
 '22.',
 '23.',
 '24.',
 '25.',
 '26.',
 '27.',
 '28.',
 '29.',
 '30.']

In [7]:
# Scraoing Name of the videos
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[2]"):
        Name.append(i.text)
except NoSuchElementException:
    Name.append("_")

Name

['"Baby Shark Dance"[3]',
 '"Despacito"[6]',
 '"Johny Johny Yes Papa"[12]',
 '"Shape of You"[13]',
 '"See You Again"[15]',
 '"Bath Song"[20]',
 '"Phonics Song with Two Words"[21]',
 '"Uptown Funk"[22]',
 '"Learning Colors – Colorful Eggs on a Farm"[23]',
 '"Gangnam Style"[24]',
 '"Masha and the Bear – Recipe for Disaster"[29]',
 '"Wheels on the Bus"[30]',
 '"Dame Tu Cosita"[31]',
 '"Sugar"[32]',
 '"Roar"[33]',
 '"Counting Stars"[34]',
 '"Sorry"[35]',
 '"Thinking Out Loud"[36]',
 '"Axel F"[37]',
 '"Baa Baa Black Sheep"[38]',
 '"Dark Horse"[39]',
 '"Faded"[40]',
 '"Girls Like You"[41]',
 '"Let Her Go"[42]',
 '"Bailando"[43]',
 '"Lean On"[44]',
 '"Perfect"[45]',
 '"Waka Waka (This Time for Africa)"[46]',
 '"Shake It Off"[47]',
 '"Mi Gente"[48]']

In [8]:
# Scraping Artist of the video
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[3]"):
        Artist.append(i.text)
except NoSuchElementException:
    Artist.append("_")
Artist

["Pinkfong Baby Shark - Kids' Songs & Stories",
 'Luis Fonsi',
 'LooLoo Kids',
 'Ed Sheeran',
 'Wiz Khalifa',
 'Cocomelon – Nursery Rhymes',
 'ChuChu TV',
 'Mark Ronson',
 'Miroshka TV',
 'Psy',
 'Get Movies',
 'Cocomelon – Nursery Rhymes',
 'El Chombo',
 'Maroon 5',
 'Katy Perry',
 'OneRepublic',
 'Justin Bieber',
 'Ed Sheeran',
 'Crazy Frog',
 'Cocomelon – Nursery Rhymes',
 'Katy Perry',
 'Alan Walker',
 'Maroon 5',
 'Passenger',
 'Enrique Iglesias',
 'Major Lazer',
 'Ed Sheeran',
 'Shakira',
 'Taylor Swift',
 'J Balvin']

In [9]:
# Scraping Uploaded date of the video
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[5]"):
        UploadDate.append(i.text)
except NoSuchElementException:
    UploadDate.append("_")

UploadDate

['June 17, 2016',
 'January 12, 2017',
 'October 8, 2016',
 'January 30, 2017',
 'April 6, 2015',
 'May 2, 2018',
 'March 6, 2014',
 'November 19, 2014',
 'February 27, 2018',
 'July 15, 2012',
 'January 31, 2012',
 'May 24, 2018',
 'April 5, 2018',
 'January 14, 2015',
 'September 5, 2013',
 'May 31, 2013',
 'October 22, 2015',
 'October 7, 2014',
 'June 16, 2009',
 'June 25, 2018',
 'February 20, 2014',
 'December 3, 2015',
 'May 31, 2018',
 'July 25, 2012',
 'April 11, 2014',
 'March 22, 2015',
 'November 9, 2017',
 'June 4, 2010',
 'August 18, 2014',
 'June 29, 2017']

In [10]:
# Scraping Views of videos
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]"):
        Views.append(i.text)
except NoSuchElementException:
    Views.append("_")
Views

['11.09',
 '7.94',
 '6.41',
 '5.78',
 '5.59',
 '5.55',
 '4.79',
 '4.65',
 '4.60',
 '4.51',
 '4.50',
 '4.25',
 '4.01',
 '3.74',
 '3.63',
 '3.62',
 '3.57',
 '3.48',
 '3.46',
 '3.32',
 '3.32',
 '3.32',
 '3.32',
 '3.27',
 '3.25',
 '3.24',
 '3.22',
 '3.21',
 '3.19',
 '3.12']

In [11]:
# Creating DataFrame from scraped data
Wiki = pd.DataFrame({})
Wiki['Rank']=Rank
Wiki['Name']=Name
Wiki['Artist']=Artist
Wiki['Upload Date']=UploadDate
Wiki['Views']=Views

# Removing stray numbers from Name column
Wiki.Name = Wiki.Name.apply(lambda x:x[:-4].strip('"'))
Wiki

,Rank,Name,Artist,Upload Date,Views
0,1.,Baby Shark Dance,Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",11.09
1,2.,Despacito,Luis Fonsi,"January 12, 2017",7.94
2,3.,Johny Johny Yes Papa,LooLoo Kids,"October 8, 2016",6.41
3,4.,Shape of You,Ed Sheeran,"January 30, 2017",5.78
4,5.,See You Again,Wiz Khalifa,"April 6, 2015",5.59
5,6.,Bath Song,Cocomelon – Nursery Rhymes,"May 2, 2018",5.55
6,7.,Phonics Song with Two Words,ChuChu TV,"March 6, 2014",4.79
7,8.,Uptown Funk,Mark Ronson,"November 19, 2014",4.65
8,9.,Learning Colors – Colorful Eggs on a Farm,Miroshka TV,"February 27, 2018",4.60
9,10.,Gangnam Style,Psy,"July 15, 2012",4.51
10,11.,Masha and the Bear – Recipe for Disaster,Get Movies,"January 31, 2012",4.50
11,12.,Wheels on the Bus,Cocomelon – Nursery Rhymes,"May 24, 2018",4.25
12,13.,Dame Tu Cosita,El Chombo,"April 5, 2018",4.01
13,14.,Sugar,Maroon 5,"January 14, 2015",3.74
14,15.,Roar,Katy Perry,"September 5, 2013",3.63
15,16.,Counting Stars,OneRepublic,"May 31, 2013",3.62
16,17.,Sorry,Justin Bieber,"October 22, 2015",3.57
17,18.,Thinking Out Loud,Ed Sheeran,"October 7, 2014",3.48
18,19.,Axel F,Crazy Frog,"June 16, 2009",3.46
19,20.,Baa Baa Black Sheep,Cocomelon – Nursery Rhymes,"June 25, 2018",3.32
20,21.,Dark Horse,Katy Perry,"February 20, 2014",3.32
21,22.,Faded,Alan Walker,"December 3, 2015",3.32
22,23.,Girls Like You,Maroon 5,"May 31, 2018",3.32
23,24.,Let Her Go,Passenger,"July 25, 2012",3.27
24,25.,Bailando,Enrique Iglesias,"April 11, 2014",3.25
25,26.,Lean On,Major Lazer,"March 22, 2015",3.24
26,27.,Perfect,Ed Sheeran,"November 9, 2017",3.22
27,28.,Waka Waka (This Time for Africa),Shakira,"June 4, 2010",3.21
28,29.,Shake It Off,Taylor Swift,"August 18, 2014",3.19
29,30.,Mi Gente,J Balvin,"June 29, 2017",3.12

# Q2

In [12]:
# Getting the webpage of mentioned url 
url=('https://www.bcci.tv/')
driver.get(url)

In [13]:
button=driver.find_element(By.XPATH,'/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a')
driver.get(button.get_attribute("href"))
time.sleep(3)

In [14]:
# Creating empty lists for scraping the data

MatchTitle = []
Series = []
Place = []
Date = []
Time = []

In [15]:
for i in driver.find_elements(By.XPATH,'//span[@class="matchOrderText ng-binding ng-scope"]'):
    MatchTitle.append(i.text)
MatchTitle

['1st ODI -',
 '2nd ODI -',
 '3rd ODI -',
 '1st T20I -',
 '2nd T20I -',
 '1st T20I -',
 '2nd T20I -',
 '3rd T20I -']

In [16]:
for i in driver.find_elements(By.XPATH,'//span[@class="ng-binding"]'):
    Series.append(i.text)
Series

['INDIA TOUR OF ZIMBABWE ODI SERIES 2022',
 'INDIA TOUR OF ZIMBABWE ODI SERIES 2022',
 'INDIA TOUR OF ZIMBABWE ODI SERIES 2022',
 'ASIA CUP 2022',
 'ASIA CUP 2022',
 'AUSTRALIA TOUR OF INDIA T20 SERIES 2022',
 'AUSTRALIA TOUR OF INDIA T20 SERIES 2022',
 'AUSTRALIA TOUR OF INDIA T20 SERIES 2022']

In [17]:
for i in driver.find_elements(By.XPATH,'//span[@class="ng-binding ng-scope"]'):
    Place.append(i.text)
Place

['Harare Sports Club,',
 'Harare Sports Club,',
 'Harare Sports Club,',
 'Dubai International Cricket Stadium,',
 'Dubai International Cricket Stadium,',
 'Punjab Cricket Association IS Bindra Stadium,',
 'Vidarbha Cricket Association Stadium,',
 'Rajiv Gandhi International Stadium,']

In [18]:
for i in driver.find_elements(By.XPATH,'//h5[@class="ng-binding"]'):
    Date.append(i.text)
Date

['18 AUG 2022',
 '20 AUG 2022',
 '22 AUG 2022',
 '28 AUG 2022',
 '31 AUG 2022',
 '20 SEP 2022',
 '23 SEP 2022',
 '25 SEP 2022']

In [19]:
for i in driver.find_elements(By.XPATH,'//h5[@class="text-right ng-binding"]'):
    Time.append(i.text)
Time

['12:45 PM IST',
 '12:45 PM IST',
 '12:45 PM IST',
 '7:30 PM IST',
 '7:30 PM IST',
 '7:30 PM IST',
 '7:30 PM IST',
 '7:30 PM IST']

# Q3

In [19]:
driver=webdriver.Chrome('chromedriver.exe')

C:\Users\DELL\AppData\Local\Temp/ipykernel_2040/101893016.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome('chromedriver.exe')

In [20]:
url = ("https://www.guru99.com/")
driver.get(url)

In [21]:
Name = []
Description = []

In [ ]:
# clicking on Selenium button
driver.find_element(By.XPATH,"//li//a[@title='Selenium']").click()

# clicking on Exception Handling button
driver.find_element(By.XPATH,'//a[@title="Selenium Exception Handling (Common Exceptions List)"]').click()

# scraping Name
for i in driver.find_elements(By.XPATH,"//table[@class='table table-striped']/tbody/tr/td[1]"):
    Name.append(i.text)
    
# scraping Description
for i in driver.find_elements(By.XPATH,"//table[@class='table table-striped']/tbody/tr/td[2]"):
    Description.append(i.text)

    
# creating the dataframe from the scraped data
Selenium = pd.DataFrame({})
Selenium['Exception_Name'] = Name
Selenium['Description'] = Description
Selenium

# Q5

In [46]:
# activate  chrome browser
driver=webdriver.Chrome('chromedriver.exe')

#  url
url=('https://github.com/')
driver.get(url)
time.sleep(5)
try:
    link_trending = driver.find_element(By.XPATH,'/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a').get_attribute('href')
except NoSuchElementException:
    print("Trending xpath could not be found")

driver.get(link_trending)
time.sleep(5)
# Let's create an empty lists to store scraping data
Repository_Title=[]
Repository_Description=[] 
Contributors_Count=[] 
Language_Used=[]
urls=[]

# Let's create a function
try:
    rep_title=driver.find_elements(By.XPATH,'//article[@class="Box-row"]/h1/a')
except NoSuchElementException:
    print("Title xpath could not be found")
try:
    descriptions=driver.find_elements(By.XPATH,'//article[@class="Box-row"]/p')
except NoSuchElementException:
    print("Description xpath could not be found")
for i in [rep_title,descriptions]:
    for j in i:
        if i ==rep_title:
            Repository_Title.append(j.text)
            urls.append(j.get_attribute('href'))
        if i==descriptions:
            Repository_Description.append(j.text)
for url in urls:
    driver.get(url)
    driver.implicitly_wait(3)
    div_list=driver.find_elements(By.XPATH,'//div[@class="BorderGrid BorderGrid--spacious"]/div')
    try:
        Contributors_Count.append(((div_list[-2].text).split())[1])
    except:
        Contributors_Count.append('-')
    try:
        Language_Used.append(((div_list[-1].text).split())[1::2])
    except:
        Language_Used.append('-')

# Let's check the length of the scrape data        
print(len(Repository_Title),len(Repository_Description),len(Contributors_Count),len(Language_Used))


# L3t's create the dataframe from the scraped data
Repositoriy=pd.DataFrame({})
Repositoriy['Repository Title']=Repository_Title[0:24]
Repositoriy['Repository Description']=Repository_Description[0:24]
Repositoriy['Contributors Count']=Contributors_Count[0:24]
Repositoriy['Language Used']=Language_Used[0:24]
Repositoriy

C:\Users\DELL\AppData\Local\Temp/ipykernel_2416/2430864428.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome('chromedriver.exe')

25 24 25 25

,Repository Title,Repository Description,Contributors Count,Language Used
0,pacocoursey / cmdk,"Fast, unstyled command menu React component.",6,"[TypeScript, SCSS, Other]"
1,TheAlgorithms / Python,All Algorithms implemented in Python,826,[Python]
2,InterviewReady / system-design-resources,These are the best resources for System Design...,-,[5]
3,Alcibiades-Capital / mev_bundle_generator,A MEV bundle generator written in Rust,-,"[Rust, Solidity]"
4,craftzdog / dotfiles-public,My personal dotfiles,7,"[Lua, Shell, PowerShell]"
5,hasura / graphql-engine,"Blazing fast, instant realtime GraphQL APIs on...",454,"[Haskell, TypeScript, JavaScript, Go, Python, ..."
6,eugeneyan / applied-ml,📚 Papers & tech blogs by companies sharing the...,-,"[38, 27]"
7,MatrixTM / MHDDoS,"Best DDoS Attack Script Python3, (Cyber / DDos...",27,"[Python, Dockerfile]"
8,onekey-sec / unblob,Extract files from any kind of container formats,10,"[Python, Nix, Other]"
9,rad9800 / TamperingSyscalls,A complete computer science study plan to beco...,2,"[C++, Python]"
10,jwasham / coding-interview-university,There can be more than Notion and Miro. Affine...,by,"[255, 244]"
11,toeverything / AFFiNE,Convert AI papers to GUI，Make it easy and conv...,16,"[TypeScript, JavaScript, CSS, HTML, Shell, SCSS]"
12,Baiyuetribe / paper2gui,30 Days of React challenge is a step by step g...,-,"[Jupyter, 100.0%]"
13,Asabeneh / 30-Days-Of-React,DuckDB is an in-process SQL OLAP Database Mana...,8,"[JavaScript, HTML, Other]"
14,duckdb / duckdb,"A precise specification for ""Rust lite / MIR p...",143,"[C++, C, Python, JavaScript, Julia, Java, Other]"
15,RalfJung / minirust,The Metadata Platform for the Modern Data Stack,-,[5]
16,datahub-project / datahub,Qlib is an AI-oriented quantitative investment...,259,"[Java, Python, TypeScript, JavaScript, Shell, ..."
17,microsoft / qlib,🧑‍🏫 50! Implementations/tutorials of deep lear...,97,"[Python, Cython]"
18,labmlai / annotated_deep_learning_paper_implem...,Collection of publicly available IPTV channels...,13,"[Jupyter, 59.3%, 40.7%]"
19,iptv-org / iptv,智能微秘书客户端，搭配,181,"[JavaScript, Shell]"
20,leochen-g / wechat-assistant-pro,AirPlay 2 Receiver - Python implementation,-,"[JavaScript, Dockerfile]"
21,openairplay / airplay2-receiver,List of Computer Science courses with video le...,13,"[Python, Other]"
22,Developer-Y / cs-video-courses,Build faster websites with Astro's next-gen is...,-,"[69, 58]"
23,withastro / astro,⚡️ Express inspired web framework written in Go,298,"[TypeScript, JavaScript, Astro, Vue, Svelte, C..."

# Q7

In [5]:
driver=webdriver.Chrome('chromedriver.exe')

driver.maximize_window()
# Getting the webpage of mentioned url 
url=('https://www.naukri.com/')
driver.get(url)
time.sleep(2)

C:\Users\DELL\AppData\Local\Temp/ipykernel_2040/127667065.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome('chromedriver.exe')

In [8]:
#Fetching urls to navigate recruiter page
recruiter = driver.find_element(By.XPATH,'//a[@title="Search Jobs"]')
page_url = recruiter.get_attribute("href")

driver.get(page_url)
time.sleep(3)

In [9]:
#Fetching urls to navigate recruiter page
recruiter = driver.find_element(By.XPATH,'/html/body/div[1]/div/ul/li[2]/a')
page_url = recruiter.get_attribute("href")

driver.get(page_url)
time.sleep(3)

In [10]:
search = driver.find_element(By.XPATH,"//div[@class='inpWrap']//input") 
search.send_keys("Data science ")           
btn = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/button').click()     
time.sleep(3)

In [12]:
#Creating empty lists
Name = []
Designation = []
Company = []
Skills = []
Location = []

In [13]:
#Scraping data of Names
for i in driver.find_elements(By.XPATH,"//span[@class='fl ellipsis']"):
    Name.append(i.text)
time.sleep(3)

#Scraping data of Designation
for i in driver.find_elements(By.XPATH,"//span[@class='ellipsis clr']"):
    Designation.append(i.text)
    
#Scraping data of company name
for i in driver.find_elements(By.XPATH,"//div[@class='vcard']//p[1]/a[2]"):
    Company.append(i.text)

#Scraping data of locations
for i in driver.find_elements(By.XPATH,"//div[@class='vcard']//p[1]//span"):
    Location.append(i.text)
time.sleep(3)

In [14]:
print(len(Name),len(Designation),len(Company),len(Location))

50 50 50 148

In [15]:
# Creating dataframe for scraped data
Naukri=pd.DataFrame({})
Naukri['Name'] = Name
Naukri['Designation'] = Designation
Naukri['Company'] = Company
Naukri['Location'] = Location[:50]
Naukri

,Name,Designation,Company,Location
0,Aakash Harit,HR Manager,Data Science Network,Aakash Harit
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,HR Manager
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,Delhi
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,shravan Kumar Gaddam
4,subhas patel,Founder CEO,LibraryXProject,Company Recruiter
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,Hyderabad / Secunderabad
6,Institute for Financial Management and Resear,Programme Manager,IFMR,MARSIAN Technologies LLP
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,Company HR
8,Asif Lucknowi,Director,Weupskill- Live Wire India,Pune
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,Anik Agrawal
10,Vaishnavi Kudalkar,HR Executive,Codeachive learning,Company Recruiter
11,Priyanka Akiri,HR Manager,Infinitive Software Solutions,Ahmedabad
12,Kalpana Dumpala,Executive Hiring,Innominds Software,subhas patel
13,Mubarak,Company HR,MoneyTap,Founder CEO
14,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,UK - (london)
15,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,Abhishek - Only Analytics Hiring - India and
16,Kapil Devang,HR Manager,BISP Solutions,Recruitment Lead Consultant
17,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,Vadodara / Baroda
18,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,Institute for Financial Management and Resear
19,Manisha Yadav,HR Executive,Easi Tax,Programme Manager
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Chennai
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,Balu Ramesh
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,HR Administrator
23,Rithika dadwal,HR Recruiter,Affine Analytics,Trivandrum
24,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,Asif Lucknowi
25,Shaun Rao,Manager Human Resources,Exela Technologies,Director
26,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,Indore
27,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,InstaFinancials
28,kumar,Proprietor,trainin,Human Resource
29,Sunil Vedula,CEO,Nanoprecise Sci Corp,Bengaluru / Bangalore
30,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,Vaishnavi Kudalkar
31,Dhruv Dev Dubey,Company Recruitment Head,Confidential,HR Executive
32,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd",Mumbai
33,Avodha,Business Development Associate,Nikitha Palaparthi,Priyanka Akiri
34,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,HR Manager
35,Priya Khare,Senior Manager,Independent Consultant,Hyderabad
36,Amit Sharma,Consultant,ASCO consulting,Kalpana Dumpala
37,Kanan,senior technology instructor,NY INST,Executive Hiring
38,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,Hyderabad / Secunderabad
39,Brad,"Manager, Technical Recruiting",O.C. Tanner,Mubarak
40,Rutuja Pawar,Technical Recruiter,Demand Matrix,Company HR
41,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,Bengaluru / Bangalore
42,Ankit Sinha,Head Analytics,Suntech Global,Kushal Rastogi
43,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,Company HR
44,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,Mumbai
45,Ashwini,Director Global Delivery,MRP Advisers,Mahesh Babu Channa
46,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,HR Team Lead
47,Rajani Nagaraj,HR Manager,WildJasmine,Hyderabad / Secunderabad
48,ROHIT Kumar,Architect,LNT Private Limited,Kapil Devang
49,Amir Chowdhury,Managing Partner,Granular.ai,HR Manager

# Q8

In [43]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the theguardian.com
url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare"
driver.get(url)
time.sleep(2)

#scrapping book names
book_name=[]
try:
    names=driver.find_elements(By.XPATH,"//table[@class='in-article sortable']/tbody/tr/td[2]")
    for i in names:
        book_name.append(i.text)
except NoSuchElementException:              #handling no such element exception
    book_name.append('No details available')
time.sleep(2)

#scrapping author names
author_name=[]
try:
    names=driver.find_elements(By.XPATH,"//table[@class='in-article sortable']/tbody/tr/td[3]")
    for i in names:
        author_name.append(i.text)
except NoSuchElementException:#handling no such element exception
    author_name.append('No details available')
time.sleep(2)


#scrapping Sale
Sale=[]
try:
    sale=driver.find_elements(By.XPATH,"//table[@class='in-article sortable']/tbody/tr/td[4]")
    for i in sale:
        Sale.append(i.text)
except NoSuchElementException:#handling no such element exception
    Sale.append('No details available')
time.sleep(2)    
#scrapping publisher
publisher=[]
try:
    publishers=driver.find_elements(By.XPATH,"//table[@class='in-article sortable']/tbody/tr/td[5]")
    for i in publishers:
        publisher.append(i.text)
except NoSuchElementException:#handling no such element exception
    publisher.append('No details available')
time.sleep(2)

#scrapping genre
genre=[]
try:
    genres=driver.find_elements(By.XPATH,"//table[@class='in-article sortable']/tbody/tr/td[6]")
    for i in genres:
        genre.append(i.text)
except NoSuchElementException:#handling no such element exception
    genre.append('No details available')
time.sleep(2)

#creating dataframe
df=pd.DataFrame({"Book_name":book_name,
                "Author_name":author_name,
                'Volume sold':Sale,
                'Publisher':publisher,
                'Genre':genre})
df

C:\Users\DELL\AppData\Local\Temp/ipykernel_2416/1013279962.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("chromedriver.exe")

,Book_name,Author_name,Volume sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# Q9

In [44]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the imdb.com
url = "https://www.imdb.com/list/ls095964455"
driver.get(url)
time.sleep(2)

# scraping name of webseries
name=[]
try:
    names=driver.find_elements(By.XPATH,"//h3[@class='lister-item-header']/a")
    for i in names:
        name.append(i.text)
except NosuchElementException:#handling no such element exception
    name.append('No details available')
time.sleep(2)


# scraping year of release
years=[]
try:
    span=driver.find_elements(By.XPATH,"//h3[@class='lister-item-header']/span[2]")
    for i in span:
        years.append(i.text)
except NosuchElementException:#handling no such element exception
    years.append('No details available')
time.sleep(2)


# scraping genre
genre=[]
try:
    genres=driver.find_elements(By.XPATH,"//span[@class='genre']")
    for i in genres:
        genre.append(i.text)
except NoSuchElementException:#handling no such element exception
    genre.append('No details available')
time.sleep(2)
# scraping run_time
run_time=[]
try:
    info=driver.find_elements(By.XPATH,"//span[@class='runtime']")
    for i in info:
        run_time.append(i.text)
except NoSuchElementException:#handling no such element exception
    run_time.append('No details available')
time.sleep(2)


# scraping rating
rating=[]
try:
    info=driver.find_elements(By.XPATH,"//div[@class='ipl-rating-star small']/span[2]")
    for i in info:
        rating.append(i.text)
except NoSuchElementException:#handling no such element exception
    rating.append('No details available')
time.sleep(2)

# scraping votes
votes=[]
try:
    info=driver.find_elements(By.XPATH,"//span[@name='nv']")
    for i in info:
        votes.append(i.text)
except NoSuchElementException:#handling no such element exception
    votes.append('No details available')
time.sleep(2)


#creating dataframe
df=pd.DataFrame({"Name":name,
                "years":years,
                "Genre":genre,
                "Run_time":run_time,
                "Rating":rating,
                "Votes":votes})
df

C:\Users\DELL\AppData\Local\Temp/ipykernel_2416/2769471088.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("chromedriver.exe")

,Name,years,Genre,Run_time,Rating,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,021,629"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"1,118,247"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"959,869"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"286,956"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"246,552"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.4,"49,269"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"60,167"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"193,422"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"40,808"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"233,409"

# Q10

In [45]:

# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the imdb.com
url = "https://archive.ics.uci.edu/"
driver.get(url)
time.sleep(2)

#clicking show all datasets link
show=driver.find_element(By.XPATH,"//a[@href='datasets.php']")
show.click()
time.sleep(1)


#scraping dataset names
name=[]
try:
    names=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")
    for i in names:
        name.append(i.text)
except NoSuchElementException:#handling no such element exception
    name.append('No details available')
time.sleep(2)

#scraping data type
data_type=[]
try:
    info=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")
    for i in info[1:]:
         data_type.append(i.text)
except NoSuchElementException:
    data_type.append("No information")
time.sleep(2)
#scraping dataset names
default_task=[]
try:
    info=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]")
    for i in info[1:]:
         default_task.append(i.text)
except NoSuchElementException:
    default_task.append("No information")
time.sleep(2)


#scraping dataset names
attr_type=[]
try:
    info=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]")
    for i in info[1:]:
         attr_type.append(i.text)
except NoSuchElementException:
    attr_type.append("No information")
time.sleep(2)


#scraping dataset names
no_of_instances=[]
try:
    info=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]")
    for i in info[1:]:
         no_of_instances.append(i.text)
except NoSuchElementException:
    no_of_instances.append("No information")
time.sleep(2)


#scraping dataset names
no_of_attributes=[]
try:
    info=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]")
    for i in info[1:]:
         no_of_attributes.append(i.text)
except NoSuchElementException:
    no_of_attributes.append("No information")
time.sleep(2)


#scraping dataset names
year=[]
try:
    info=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]")
    for i in info[1:]:
         year.append(i.text)
except NoSuchElementException:
    year.append("No information")
time.sleep(2)

#creating dataframe
df=pd.DataFrame({'Name':name,
                'Data_type':data_type,
                'Task':default_task,
                'Attribute_type':attr_type,
                'No_of_instances':no_of_instances,
                'No_of_attributes':no_of_attributes,
                'Year':year})
df

C:\Users\DELL\AppData\Local\Temp/ipykernel_2416/3206361981.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("chromedriver.exe")

,Name,Data_type,Task,Attribute_type,No_of_instances,No_of_attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021